global:
  scrape_interval: 15s  # 15초마다 메트릭을 스크랩

scrape_configs:
  # mongle-server 컨테이너의 메트릭 수집
  - job_name: 'mongle-server'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'mongle-server:3000' ]  # Docker Compose의 NestJS 컨테이너와 포트 지정

  # Prometheus 자체 메트릭 수집
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
