apiVersion: 1

datasources:
  # PostgreSQL 데이터 소스 설정
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable

