apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mgmg.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mgmg.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
  selector:
    matchLabels:
      {{- include "mgmg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mgmg.selectorLabels" . | nindent 8 }}
    spec:
      revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1

        env:
        {{- toYaml .Values.env | nindent 8 }}
        {{- if .Values.configMap }}
        volumeMounts:
        - name: env-config
          mountPath: {{ .Values.configMap.mountPath }}
          subPath: .env 
        {{- end }}
      {{- if .Values.configMap }}
      volumes:
      - name: env-config
        configMap:
          name: {{ .Values.configMap.name }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }} 