apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgmg.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mgmg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "mgmg.selectorLabels" . | nindent 4 }} 