apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgmg
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgmg
  template:
    metadata:
      labels:
        app: mgmg
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
      - name: mgmg
        image: {{env.AWS_ACCOUNT_ID}}.dkr.ecr.ap-northeast-2.amazonaws.com/mgmg:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "dev"
        - name: LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: env-config
          mountPath: /app/config
      volumes:
      - name: env-config
        configMap:
          name: mgmg-env
      imagePullSecrets:
      - name: ecr-secret